# Generated by Django 3.0.6 on 2020-12-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogbook',
            name='blog',
        ),
        migrations.AddField(
            model_name='blogbook',
            name='blog',
            field=models.ManyToManyField(to='blog.BlogPost'),
        ),
    ]
